= CodeRAD 2 Sampler

This project includes a collection of samples that demonstrate the usage of CodeRAD components.

== Running the Project

Download or clone this repository, then open the project in IntelliJ.

Then press the "Run" button.

[NOTE]
.Dependencies
====
Dependencies in this repository point to _SNAPSHOT_ versions of both Codename One and CodeRAD.  In order to run this project, you'll either need to change the dependencies in the link:pom.xml[] file and the link:common/pom.xml[] XML file to point to release versions, or you need to install Codename One and CodeRAD into your local Maven repository.

At time of writing the latest Codename One release version is 7.0.33.  You can update this project to point to this version by changing the `cn1.version` and `cn1.plugin.version` properties in the link:pom.xml[] file.  You an find the latest release version of Codename One https://search.maven.org/search?q=codenameone-maven-plugin[here].

At the time of writing, the latest version of CodeRAD is 2.0-pre4.  You can update this project to use this version by changing the `<version>` for the `coderad-annotion-processor` dependency in the link:pom.xml[] and the `coderad-lib` dependency in the link:common/pom.xml[] file.  You can find the latest version of CodeRAD https://search.maven.org/artifact/com.codenameone/coderad-lib[here].
====

== CodeRAD View Samples

The link:common/src/main/rad/views/com/codename1/rad/sampler[com.codename1.rad.sampler] views package includes some sample CodeRAD views.

== Java Source

Most of the app's Java source code can be found in the link:common/src/main/java/com/codename1/rad/sampler[com.codename1.rad.sampler] package in the common module.

== Learn More

. https://github.com/shannah/CodeRAD[CodeRAD] - The CodeRAD Github Repository includes all the information you need to get started building iOS and Android apps using CodeRAD.
. https://www.codenameone.com[Codename One Website] - CodeRAD is built upon Codename One, a toolkit for building truly native, mobile-first, pixel-perfect apps in Java and Kotlin.

== Credits

This project created by https://sjhannah.com[Steve Hannah].