package com.codename1.rad.sampler;

import com.codename1.rad.controllers.ApplicationController;
import com.codename1.rad.controllers.ControllerEvent;
import com.codename1.rad.sampler.providers.SampleListProvider;

import static com.codename1.rad.util.NonNull.with;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class Coderad2Samples extends ApplicationController {



    public void actionPerformed(ControllerEvent evt) {

        with(evt, StartEvent.class, startEvent -> {
            if (!startEvent.isShowingForm()) {
                startEvent.setShowingForm(true);
                new StartPageController(this).show();
            }
        });
        super.actionPerformed(evt);
    }

    @Override
    protected void onStartController() {
        super.onStartController();
        addLookup(new SampleListProvider());
    }
}
